# pack.py: baked plate PNGs → short/plates/plates.js (JPEG data URIs), so the page can load them from file://
# without tainting the canvas. Run after rendering the plate_* loops (see short/src/plates.js).
# Grade: the plates are painted in mid-tones (watercolour pigment only darkens), then each channel is moved to the
# night ground and its texture stretched, out = (in - mean) * GAIN + TARGET, so the blooms read on a phone.
import base64, glob, io, os
from PIL import Image, ImageStat
H = os.path.dirname(os.path.abspath(__file__))
TARGET, GAIN = (25, 28, 31), 1.9
out = ['// generated by short/plates/pack.py from the baked plate_* loops', 'window.PLATE_SRC = {']
for d in sorted(glob.glob(f'{H}/raw_*')):
    name, png = os.path.basename(d)[4:], sorted(glob.glob(f'{d}/*.png'))[0]
    img = Image.open(png).convert('RGB'); mean = ImageStat.Stat(img).mean
    bands = [b.point(lambda v, m=m, t=t: max(0, min(255, round((v - m) * GAIN + t)))) for b, m, t in zip(img.split(), mean, TARGET)]
    graded = Image.merge('RGB', bands); graded.save(f'{H}/{name}.jpg', quality=90)
    buf = io.BytesIO(); graded.save(buf, 'JPEG', quality=90)
    out.append(f"  {name}: 'data:image/jpeg;base64,{base64.b64encode(buf.getvalue()).decode()}',")
    print(name, len(buf.getvalue()) // 1024, 'KB, mean in', [round(m) for m in mean], '→', [round(m) for m in ImageStat.Stat(graded).mean])
out.append('};')
open(f'{H}/plates.js', 'w').write('\n'.join(out) + '\n')
